name: test-publish-action
on:
  push:
    tags:
      - 'v*'
jobs:
  run-godel-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/cache@v2
        with:
          path: |
            ~/.godel
          key: ${{ runner.os }}-godel-${{ hashFiles('godelw', 'godel/config/godel.yml') }}
          restore-keys: |
            ${{ runner.os }}-godel-
      - run: ./godelw dist
        env:
          GOPATH: "/home/runner/go"
      - run: ./godelw publish github --dry-run --add-v-prefix --api-url=$GITHUB_API_URL --user=nmiyake --repository=godel-generate-plugin --token=${{ secrets.GITHUB_TOKEN }}
        env:
          GOPATH: "/home/runner/go"
